# Generated by Django 5.2.1 on 2025-05-21 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idiomas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Idioma', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'idiomas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Modulos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('conteudo1', models.CharField(max_length=250)),
                ('conteudo2', models.CharField(max_length=250)),
                ('conteudo3', models.CharField(max_length=250)),
                ('conteudo4', models.CharField(max_length=250)),
                ('conteudo5', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'modulos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cur_Academicos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('curso', models.CharField(max_length=40)),
                ('istituicao', models.CharField(max_length=40)),
                ('descricao', models.CharField(max_length=250)),
                ('dt_inicio', models.DateField()),
                ('dt_final', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_academico', to='app.authuser')),
            ],
            options={
                'db_table': 'cur_academico',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cur_Carreiras',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cargo', models.CharField(max_length=40)),
                ('empresa', models.CharField(max_length=40)),
                ('descricao', models.CharField(max_length=250)),
                ('dt_inicio', models.DateField()),
                ('dt_final', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_carreira', to='app.authuser')),
            ],
            options={
                'db_table': 'cur_carreira',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cur_Pessoal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('telefone', models.CharField(max_length=16)),
                ('celular', models.CharField(max_length=16)),
                ('estado', models.CharField(max_length=2)),
                ('Cidade', models.CharField(max_length=40)),
                ('bairro', models.CharField(max_length=40)),
                ('rua', models.CharField(max_length=40)),
                ('numero', models.CharField(max_length=4)),
                ('links', models.CharField(max_length=60)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pessoal', to='app.authuser')),
            ],
            options={
                'db_table': 'cur_pessoal',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=40)),
                ('descricao', models.CharField(max_length=100)),
                ('qnt_modulo', models.IntegerField()),
                ('valor', models.FloatField()),
                ('gratis', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_curso', to='app.authuser')),
            ],
            options={
                'db_table': 'cursos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Modulos_Cursos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nivel', models.IntegerField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curso_n_modulo', to='app.cursos')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulo_n_curso', to='app.modulos')),
            ],
            options={
                'db_table': 'modulos_cursos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User_Cursos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curso_n_user', to='app.cursos')),
                ('modulo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modulo_curso', to='app.modulos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_n_curso', to='app.authuser')),
            ],
            options={
                'db_table': 'user_cursos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User_Idiomas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nivel', models.CharField(max_length=20)),
                ('idioma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idioma_n_user', to='app.idiomas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_n_idioma', to='app.authuser')),
            ],
            options={
                'db_table': 'user_idiomas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vagas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=40)),
                ('empresa', models.CharField(max_length=40)),
                ('descricao', models.CharField(max_length=250)),
                ('beneficios', models.CharField(max_length=100)),
                ('salario', models.FloatField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_vaga', to='app.authuser')),
            ],
            options={
                'db_table': 'vagas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User_Vagas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_n_vaga', to='app.authuser')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaga_n_user', to='app.vagas')),
            ],
            options={
                'db_table': 'user_vagas',
                'managed': True,
            },
        ),
    ]
