# Generated by Django 5.2 on 2025-05-22 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_idiomas_modulos_cur_academicos_cur_carreiras_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cur_academicos',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_academico', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cur_carreiras',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_carreira', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cur_pessoal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pessoal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_curso', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_cursos',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_n_curso', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_idiomas',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_n_idioma', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_vagas',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_n_vaga', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vagas',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_vaga', to=settings.AUTH_USER_MODEL),
        ),
    ]
